name: Wait for cluster to be healthy
description: 'Waits until the OpenSearch cluster health is green'

runs:
  using: composite
  steps:
    - name: Wait for cluster to be healthy
      shell: bash
      run: |
        for i in {1..10}; do
          curl -s --fail "http://localhost:9200/_cluster/health?wait_for_status=green&timeout=5s" >/dev/null && { echo "✅ Cluster is green!"; exit 0; }
          echo "Retry $i/10..."; sleep 5
        done
        echo "❌ Cluster did not become green"; exit 1
