name: Dependabot PR actions
on: 
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

jobs:
  dependabot:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0
        with:
          token: ${{ secrets.OPENSEARCH_CI_BOT_TOKEN }}

      - name: Update the changelog
        uses: dangoslen/dependabot-changelog-helper@291c8cb629d7cd7b57ea065782c435ec2bedb138 # ratchet:dangoslen/dependabot-changelog-helper@v4.3.0
        with:
          version: 'Unreleased'

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # ratchet:stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: "Update changelog"
          branch: ${{ github.head_ref }}
          commit_user_name: dependabot[bot]
          commit_user_email: support@github.com
          commit_options: '--signoff'
