name: Update API 
on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *"
jobs:
  update-api:
    if: ${{ github.repository == 'opensearch-project/opensearch-php' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Config git to rebase
        run: git config --global pull.rebase true
      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # ratchet:shivammathur/setup-php@2.37.2
        with:
          php-version: 8.3
          extensions: yaml, zip, curl 
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: Generate API
        run: composer run generate-api 
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # ratchet:peter-evans/create-pull-request@v8.1.1
        with:
          token: ${{ secrets.OPENSEARCH_CI_BOT_TOKEN }}
          push-to-fork: opensearch-ci-bot/opensearch-php
          committer: opensearch-ci-bot <opensearch-infra@amazon.com>
          author: opensearch-ci-bot <opensearch-infra@amazon.com>
          commit-message: Updated opensearch-php to reflect the latest OpenSearch API spec (${{ steps.date.outputs.date }})
          title: Updated opensearch-php to reflect the latest OpenSearch API spec
          body: |
            Updated [opensearch-php](https://github.com/opensearch-project/opensearch-php) to reflect the latest [OpenSearch API spec](https://github.com/opensearch-project/opensearch-api-specification/releases/download/main-latest/opensearch-openapi.yaml)
            Date: ${{ steps.date.outputs.date }}
          branch: automated-api-update
          base: main
          delete-branch: true
          signoff: true
          labels: |
              autocut
