<?php

declare(strict_types=1);

/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */

namespace OpenSearch\Endpoints\SearchRelevance;

use OpenSearch\Endpoints\AbstractEndpoint;

/**
 * NOTE: This file is autogenerated using util/GenerateEndpoints.php
 */
class GetJudgments extends AbstractEndpoint
{
    protected $judgment_id;

    public function getURI(): string
    {
        $judgment_id = $this->judgment_id ?? null;
        if (isset($judgment_id)) {
            return '/_plugins/_search_relevance/judgments/' . rawurlencode($judgment_id);
        }
        return '/_plugins/_search_relevance/judgments';
    }

    public function getParamWhitelist(): array
    {
        return [
            'pretty',
            'human',
            'error_trace',
            'source',
            'filter_path'
        ];
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function setJudgmentId($judgment_id): static
    {
        if (is_null($judgment_id)) {
            return $this;
        }
        $this->judgment_id = $judgment_id;

        return $this;
    }
}
